'use client';
import { useState } from 'react';
import { Farm } from '@/lib/types';
import jsPDF from 'jspdf';

type Props = { farms: Farm[] };

export default function FarmPanel({ farms }: Props) {
  const [generated, setGenerated] = useState<string[]>([]);

  function generatePDF(farm: Farm) {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text('PM Fasal Bima Yojana - Pre-Claim Report', 20, 20);
    doc.setFontSize(12);
    doc.text(`Farmer: ${farm.owner}`, 20, 40);
    doc.text(`Location: ${farm.location}`, 20, 50);
    doc.text(`Crop: ${farm.crop} | Area: ${farm.acres} acres`, 20, 60);
    doc.text(`Alert Status: ${farm.alertStatus}`, 20, 70);
    doc.text(`Generated: ${new Date().toISOString()}`, 20, 80);
    doc.text('Satellite Evidence: NASA VIIRS flood pixels detected', 20, 90);
    doc.text(`Coordinates: ${farm.lat}, ${farm.lng}`, 20, 100);
    doc.text('Auto-generated by GeoShield — Eyes on Ground', 20, 120);
    doc.save(`preclaim_${farm.owner.replace(' ', '_')}.pdf`);
    setGenerated((g) => [...g, farm.id]);
  }

  return (
    <div className="flex flex-col flex-1 overflow-hidden">
      <div className="px-3 py-2 border-b border-gray-800 flex items-center justify-between">
        <span className="text-xs text-gray-500 uppercase tracking-widest">Registered Farms</span>
        <span className="text-xs text-green-500">WhatsApp alerts on</span>
      </div>
      <div className="flex-1 overflow-y-auto">
        {farms.map((farm) => (
          <div key={farm.id} className="px-3 py-3 border-b border-gray-800 flex items-center gap-3">
            <div className="text-xl">🌾</div>
            <div className="flex-1 min-w-0">
              <p className="text-xs font-semibold text-white truncate">{farm.owner}</p>
              <p className="text-xs text-gray-500">{farm.crop} · {farm.acres} ac · {farm.location}</p>
            </div>
            <span className={`text-xs px-2 py-0.5 rounded-full font-bold shrink-0 ${
              farm.alertStatus === 'ALERT' ? 'bg-red-900 text-red-300' :
              farm.alertStatus === 'WARNING' ? 'bg-orange-900 text-orange-300' :
              'bg-green-900 text-green-300'
            }`}>
              {farm.alertStatus}
            </span>
          </div>
        ))}
      </div>
      <div className="p-3 border-t border-gray-800 space-y-2">
        {farms.filter(f => f.alertStatus === 'ALERT').map((farm) => (
          <button
            key={farm.id}
            onClick={() => generatePDF(farm)}
            className="w-full py-2 text-xs bg-transparent border border-green-800 text-green-400 hover:bg-green-900/20 rounded-lg transition-colors"
          >
            {generated.includes(farm.id) ? '✓ Downloaded' : `📄 Pre-claim PDF — ${farm.owner}`}
          </button>
        ))}
      </div>
    </div>
  );
}