import { CrisisState } from './types';

export const mockCrisisState: CrisisState = {
  clusters: [
    {
      id: 'A',
      location: 'Badrinath Road, Nandprayag',
      lat: 30.402,
      lng: 79.321,
      count: 7,
      priority: 'CRITICAL',
      message: 'बाढ़ आ रही है, मदद चाहिए',
      parsed: '7 people trapped, flood water rising, immediate rescue needed',
      timestamp: '2 min ago',
    },
    {
      id: 'B',
      location: 'Joshimath Main Market',
      lat: 30.553,
      lng: 79.567,
      count: 3,
      priority: 'HIGH',
      message: 'घर में पानी घुस आया',
      parsed: 'Water entering homes, 3 families affected',
      timestamp: '8 min ago',
    },
    {
      id: 'C',
      location: 'Chamoli North Highway',
      lat: 30.421,
      lng: 79.331,
      count: 2,
      priority: 'MEDIUM',
      message: 'पहाड़ खिसक रहा है',
      parsed: 'Landslide risk, road partially blocked',
      timestamp: '14 min ago',
    },
  ],
  teams: [
    {
      id: 'T1',
      name: 'Chamoli NDRF Team 1',
      lat: 30.382,
      lng: 79.312,
      status: 'STANDBY',
    },
    {
      id: 'T2',
      name: 'Joshimath SDRF Team 2',
      lat: 30.541,
      lng: 79.551,
      status: 'STANDBY',
    },
    {
      id: 'T3',
      name: 'Gopeshwar Base Team 3',
      lat: 30.371,
      lng: 79.481,
      status: 'STANDBY',
    },
  ],
  farms: [
    {
      id: 'F1',
      owner: 'Ramesh Bisht',
      location: 'Nandprayag',
      lat: 30.408,
      lng: 79.315,
      crop: 'Wheat',
      acres: 2.5,
      alertStatus: 'ALERT',
    },
    {
      id: 'F2',
      owner: 'Sunita Devi',
      location: 'Karnaprayag',
      lat: 30.265,
      lng: 79.241,
      crop: 'Mustard',
      acres: 1.8,
      alertStatus: 'ALERT',
    },
    {
      id: 'F3',
      owner: 'Mohan Singh',
      location: 'Pipalkoti',
      lat: 30.473,
      lng: 79.427,
      crop: 'Rice',
      acres: 3.1,
      alertStatus: 'WARNING',
    },
  ],
  riverLevel: 3.2,
  rainfall: 78,
};